name: ubuntu-make
version: 'master'
summary: Setup your development environment on ubuntu easily
description: |
  Ubuntu Make provides a set of functionality to setup,
  maintain and personalize your developer environment easily. It will handle
  all dependencies, even those which aren't in Ubuntu itself, and install
  latest versions of the desired and recommended tools.
  .
  This is the latest master from ubuntu make, freshly built from
  https://github.com/ubuntu/ubuntu-make. It may contain even unreleased
  features!
grade: stable
confinement: classic

apps:
  umake:
    command: bin/umake
    completer: umake-completion
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/usr/lib/python3.5/site-packages:$SNAP/usr/lib/python3.5/dist-packages:$PYTHONPATH

parts:
  umake:
    source: .
    plugin: python
    organize:
      lib/python3/dist-packages/umake: lib/python3.5/site-packages/umake
    build-packages:
      - gettext
      - python3
      - python3-apt
      - python3-argcomplete
      - python3-bs4
      - python3-gi
      - python3-gnupg
      - python3-setuptools
      - python3-nose
      - python3-nose-cov
      - python3-nose-json
      - python3-pep8
      - python3-pexpect
      - python3-progressbar
      - python3-yaml
      - python3-requests
      - python3-xdg
      - dbus-x11
      - fakeroot
      - help2man
    stage-packages:
      - gir1.2-gtk-3.0
      - gir1.2-glib-2.0
      - python3
      - python3-apt
      - python3-argcomplete
      - python3-bs4
      - python3-gi
      - python3-gnupg
      - python3-progressbar
      - python3-yaml
      - python3-requests
      - python3-xdg
      - libc6
      - libuuid1
      - libreadline6
      - libtinfo5
      - libselinux1
      - libpcre3
      - libudev1
      - zlib1g
      - libbz2-1.0
      - libgcc1
      - liblzma5
  umake-completion:
    plugin: dump
    source: snap
    stage:
      - umake-completion